# Generated by Django 4.2 on 2023-07-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('mail', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
            ],
        ),
    ]
